name: 'EpicFreeGamesList Add New Game Workflow'

on:
  schedule:
    # make sure to change to:
    #  in the spring: 5 18 * * 4
    #  in the fall:   5 19 * * 4
    #  holiday daily giveaway: 5 19 * * *
    - cron: 5 19 * * 4

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  epic_free_games_list_add_new_game:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be excuted as part of the job
    steps:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.3' # The Go version to download (if necessary) and use.
      - name: Get the last free games from epic
        run: go run *.go free --inputFile epic_free_games.json --outputFile out.json
      - name: Prepare to commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: |
          rm epic_free_games.json
          mv out.json epic_free_games.json
          git add epic_free_games.json
          git commit -m "Github actions adding this week's game"
      # https://openedx.atlassian.net/wiki/spaces/AC/pages/3378348233/Writing+a+GitHub+Action+that+pushes+commits
      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push
